pipeline {
  agent any
  tools {
    maven 'maven'
    }
  stages {
    stage("build") {
      steps {
        echo 'building the application...'
      }
    }
    stage("test") {
      steps {
        echo 'testing the application...'
        dir('/var/lib/jenkins/workspace/my-app-pipeline_feature_jenkins/stocks/') {
                sh 'mvn clean test'
        }
      }
    }
    stage("deploy") {
      steps {
        echo 'deploying the application...'
      }
    }
  }
}
