pipeline {
  agent any
  stages {
    stage("build") {
      steps {
        echo 'building the application...'
      }
    }
    stage("test") {
      withMaven(
        maven: Maven) {
        sh "mvn -f /var/lib/jenkins/workspace/my-app-pipeline_feature_jenkins@2/stocks/pom.xml clean test"
        }
    }
    stage("deploy") {
      steps {
        echo 'deploying the application...'
      }
    }
  }
}
