pipeline {
  agent any
  stages {
    stage("build") {
      steps {
        echo 'building the application...'
      }
    }
    stage("test") {
      steps {
        dir('/var/lib/jenkins/workspace/my-app-pipeline_feature_jenkins/stocks/')
        sh 'mvn test'
      }
    }
    stage("deploy") {
      steps {
        echo 'deploying the application...'
      }
    }
  }
}
